# Generated by Django 4.2.23 on 2025-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
