# Generated by Django 4.2.23 on 2025-07-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='iscompleted',
            new_name='is_completed',
        ),
    ]
